/*
 ******************************************************************************
 * License Information  :  Howell Instruments, Inc.                           *
 *                         "Licensed Software" and "All rights reserved".     *
 ******************************************************************************
 *  File                : hdudispfa825comm2.c
 *
 *  Description         : This file implements the arinc 825 communications portion
 *                         of the application.
 *
 *  Compiler            : GNU gcc(GNU Tools for ARM Embedded Processors) version 5.4.1 20160919
 *
 *  Compiler options    : As per section 10.3.1 of Software Development Plan (HDU-001-002).
 *
 *  Pragma              : None
 *
 *  H/W platform        : ARM Cortex-M7 (STM32F767)
 *
 *  Portability         : None
 *
 *  Author(s)           : Vinay H
 *
 *  Version History     :
 * <Version No.>      <Author>          <Date>         <Problem Report No.>
 *
 *      1.1           Vinay H       24-Jul-2017             100064
 *      1.2           Vinay H       09-Oct-2017             100064
 *      1.3           Shruthi M N   13-Oct-2017             100083
 *      1.4           Shruthi M N   30-Oct-2017             100104
 *
 * Additional References : None
 *
 ******************************************************************************
 */
#include "hdudispfapp.h"        /* contains Engine Information System application */
#include "hdudispfdauprofile.h" /* defines the constants for ARINC 825  Message Traffic.*/
#include "hdudispfresource.h"   /* provides central location to use On Chip Peripherals*/
#include "hdudispfucos.h"       /* defines the implementation of uC/OS routines  */
#include "hdudispfarinc825.h"   /* Define the structure for an ARINC 825 Message. */
#include "hdudispfa825comm.h"   /* Routines for arinc 825 communication */
#include "hdudispfoscpu.h"    /* defines the OS configurations  */
#include "hdulibbasictypes.h"      /* Standard basic data type definitions */

#define MY_SID EISDSPLY_SID      /* Server ID for this node.         */
#define STK_DEF_VAL   0xDEADDEADU

/*Updated as per PR100083*/
/* Stack for the a825comm task.  */
T_OS_STK A825_comm2_task_stk[A825COMM_TASK_STK_SIZE] =
{
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,
  STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL,STK_DEF_VAL
};

/*
 * This counter increments if a message is received that
 * is not handled by this node.  This is an indication
 * that the filters were not set up properly.
 */
static T_UINT32 U32_a825_filter_errors = 0;


/*Static functions*/
static void A825CommTask2(void *p_data);

/*
 * Function                :  A825CommTask2
 *
 * Description             :  This task is signaled from the ARINC 825 receiver routine
 *                            to process the received message.  The task will only handle
 *                            messages that it is designed to handle.  All others will
 *                            be discarded.
 *
 * Formal parameter(s)     :  void *p_data - Pointer to the data
 *
 * Return Value            :  None
 *
 * Assumption              :  None
 *
 */


static void A825CommTask2(void *p_data)
{
   T_UINT8  u8_err = 0;
   T_A825_MESSAGE arinc_mess = {0};

   p_data=(T_UINT8 *)p_data+0;
   /*hdudispfa825comm2-A825CommTask2-DB-LLR-001*/
   while (TRUE)
   {
     /*hdudispfa825comm2-A825CommTask2-DB-LLR-002*/
      /* Wait for a message to arrive. */
      OsSemPend(Sem_a8252_commtask, 0, &u8_err);

/*------------------ Process Normal Operating Channel.   -----------------*/
      if(A8252GetMessage(NOC, &arinc_mess) != A825_RX_QUEUE_EMPTY)
      {
         /* By design, only respond to NOC messages from our own function. */
         if(HOWELL_DAU_FID == arinc_mess.sID.BID.sfid)
         {
           /*hdudispfa825comm2-A825CommTask2-DB-LLR-004*/
            U32_a825_filter_errors += AppU32NOC(&arinc_mess, A825_2);
         }
         else
         {
           /*hdudispfa825comm2-A825CommTask2-DB-LLR-005*/
            U32_a825_filter_errors += 1;
         }
      }

/*-----------------  Process Node Service Channel.   -----------------------*/
      else if(A8252GetMessage(NSC, &arinc_mess) != A825_RX_QUEUE_EMPTY)
      {
         /*Updated as per PR100083*/
         if(((MY_SID == arinc_mess.sID.PID.sid) || (MULTICAST_SID == arinc_mess.sID.PID.sid))
               && (arinc_mess.sID.PID.smt))
         {
            /*hdudispfa825comm2-A825CommTask2-DB-LLR-006*/
            /* Service a Node Service Request.  */
            U32_a825_filter_errors += AppU32NSC(&arinc_mess, A825_2);
         }
         else
         {
           /*hdudispfa825comm2-A825CommTask2-DB-LLR-007*/
            U32_a825_filter_errors += 1;
         }
      }
      else
      {
         ;/*Do nothing*/
      }
   }
}

/*
 * Function                :  A825CommInit2
 *
 * Description             :  Initialize the task to handle commands coming across the
 *                               arinc 825 bus.
 *
 * Formal parameter(s)     :  None
 *
 * Return Value            :  None
 *
 * Assumption              :  None
 *
 */

void A825CommInit2(void)
{
   /*hdudispfa825comm2-A825CommInit2-DB-LLR-002*/
   /* Create the application task.  */
   OsTaskCreate(A825CommTask2, (void *)NULL,
                        &A825_comm2_task_stk[A825COMM_TASK_STK_SIZE], A825_2_COMM_TASK_PRIO);
}

